### ISSUE TITLE
The match filter does not work for string arrays when the value is coercible to another primitive type

### ISSUE THREAD

**Issue by nexbit** [esatterwhite/tastypie-rethink#1]
Given the following thinky model:
```
const EntryCategory = thinky.createModel('entry_category', {
  id: type.string(),
  extCategories: [type.string().allowNull(false).min(1).max(50).alphanum()]
}, {
  enforce_extra: 'strict'
});
```
and the following resource:
```
const Category = SoftDeleteResource.extend({
  options: {
    queryset: Model.filter({}),
    filtering: {
      extCategories: 1
    },
    allowed: {
      list: { get: true, post: true },
      detail: { get: true, put: true, patch: true, delete: true }
    }
  },
  fields: {
    id: {type: 'char', readonly: true},
    extCategories: {type: 'array', default: () => []}
   }
}
```
If you try to apply a filter like `extCategories__match=123` it does not work as expected, because in the filter implementation:
```
  , 'match': {
    value: function (r, field, term) {
      return toField(r, field).contains(term);
    }
  }
```
`term` is a number and not a string, so the ReQl query does not return any result even if there are documents containing "123" in extCategories array.
The only elegant way (IMHO) to resolve this issue is to add an array type option to node-tastypie (see https://github.com/esatterwhite/node-tastypie/issues/14), and to force casting the filter value before applying the filter.

**Comment by esatterwhite** [comment]
@nexbit things in an array can get complex and not guaranteed to be homogeneous. I think you might really want a custom field. 

You can use actual field instances in the resource definition

```js
Resource.extend({
    all_ints: new IntArrayField({default:1})
});
```

You could  also register a field with the built in fields 
```js
Object.defineProperty(tastypie.fields, 'iarray',{
    get: function(){
        return IntArrayField;
    }
});
```

then it will work like before

```js
Resource.extend({
    all_ints: {type:'iarray', default:1}
});
```

I was also planning on breaking the reql filters out into separate modules so you could tweak them or define new ones as well. Which would also be a good option. Thats what I ended up doing with the [bookshelf implementation](https://github.com/esatterwhite/tastypie-bookshelf/tree/master/lib/resource/filters).

**Comment by esatterwhite** [comment]
@nexbit You could also do per field hydration to clean data on a particular field 

```js
Resource.extend({
   hydrate_extCategories: function( bundle ){
       bundle.object.extCategories = bundle.object.extCategories.map((val)=>{
              return ~~val;
       });

       return bundle;
   }
});
```

**Comment by esatterwhite** [comment]
@nexbit You could also make a special filter type for the use case

```js
   'smatch': {
    value: function (r, field, term) {
      return toField(r, field).contains( "" + term );
    }
  }
```

**Comment by nexbit** [comment]
Yep, I had changed the predefined `match` filter like you did above, but now I've added the `smatch` filter and restored the match one, I like the solution.
This and other fixes are in my fork of your repo, if you want to take a look. There's also the fixed implementation for the tastypie's put_detail and patch_detail methods.
P.

**Comment by nexbit** [comment]
Oh I forgot to mention that the fork is updated for tastypie 3.

**Comment by esatterwhite** [comment]
@nexbit Cool. 
Appreciate all the input / feedback!
